from setuptools import setup

setup(name="geexhp", 
      version="1.0.0", 
      description="Pipeline for synthetic spectral generation and CNN-based retrieval of planetary properties "
                  "for Earth-like exoplanets observed by the Habitable Worlds Observatory (using LUVOIR-B and Habex/SS).",
      long_description="ReadMe.md",
      author="Sarah G. A. Barbosa",
      author_email="sarahg.aroucha@gmail.com",
      packages=["geexhp"], 
      install_requires=["numpy==2.1.3",
                        "matplotlib==3.10.3",
                        "smplotlib==0.0.9",
                        "pandas==2.3.0",
                        "tqdm==4.67.1",
                        "pyarrow==20.0.0",
                        "astropy==7.1.0",
                        "fastparquet==2024.11.0",
                        "PyQt5==5.15.11",
                        "tensorflow==2.19.0",
                        "scikit-learn==1.6.1",
                        "keras-tuner==1.4.7"],
      include_package_data=True,
      package_data={'geexhp.resources': ['default_habex.txt'], 
                  'geexhp.resources.atmos_layers': ['*.csv']},
      zip_safe = False)